"""
SupabaseManager – reads/writes searches and profiles from Supabase.
"""

from __future__ import annotations
import logging
import os
from uuid import UUID
from datetime import datetime, timezone
import httpx

logger = logging.getLogger(__name__)

SUPABASE_URL = os.getenv("SUPABASE_URL", "https://exydxtitrmqulahfomxj.supabase.co")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")


def _headers():
    return {
        "apikey": SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }


def _get(path: str, params: dict = None) -> list:
    r = httpx.get(f"{SUPABASE_URL}/rest/v1/{path}", headers=_headers(), params=params, timeout=10)
    r.raise_for_status()
    return r.json()


def _patch(path: str, params: dict, body: dict) -> list:
    r = httpx.patch(f"{SUPABASE_URL}/rest/v1/{path}", headers=_headers(), params=params, json=body, timeout=10)
    r.raise_for_status()
    return r.json()


class SupabaseManager:
    # ── Profile / linking ─────────────────────────────────────────────────────

    def link_telegram_token(self, chat_id: str, token: str) -> dict | None:
        """Consume a short-lived token generated by the signed-in website."""
        try:
            token = str(UUID(token))
        except (ValueError, TypeError, AttributeError):
            return None
        rows = _get(
            "profiles",
            {
                "telegram_link_token": f"eq.{token}",
                "select": "id,email,telegram_link_expires_at",
            },
        )
        if not rows:
            return None
        profile = rows[0]
        expires_raw = profile.get("telegram_link_expires_at")
        if not expires_raw:
            return None
        try:
            expires_at = datetime.fromisoformat(str(expires_raw).replace("Z", "+00:00"))
            if expires_at <= datetime.now(timezone.utc):
                _patch(
                    "profiles",
                    {"id": f"eq.{profile['id']}"},
                    {"telegram_link_token": None, "telegram_link_expires_at": None},
                )
                return None
        except (ValueError, TypeError):
            return None

        # A Telegram chat can belong to only one profile. Re-linking intentionally
        # disconnects it from the previous profile before attaching the new one.
        _patch(
            "profiles",
            {"telegram_chat_id": f"eq.{chat_id}"},
            {"telegram_chat_id": None, "telegram_connected_at": None},
        )
        _patch(
            "profiles",
            {"id": f"eq.{profile['id']}"},
            {
                "telegram_chat_id": chat_id,
                "telegram_connected_at": datetime.now(timezone.utc).isoformat(),
                "telegram_link_token": None,
                "telegram_link_expires_at": None,
            },
        )
        logger.info(f"Linked chat_id={chat_id} with one-time token (profile={profile['id']})")
        return {"id": profile["id"], "email": profile.get("email")}

    def get_profile_by_chat(self, chat_id: str) -> dict | None:
        rows = _get("profiles", {"telegram_chat_id": f"eq.{chat_id}", "select": "id,email,telegram_chat_id"})
        return rows[0] if rows else None

    def get_all_linked_profiles(self) -> list[dict]:
        return _get("profiles", {"telegram_chat_id": "not.is.null", "select": "id,telegram_chat_id"})

    # ── Searches ──────────────────────────────────────────────────────────────

    def get_searches(self, chat_id: str, active_only: bool = True) -> list[dict]:
        profile = self.get_profile_by_chat(chat_id)
        if not profile:
            return []
        params = {"user_id": f"eq.{profile['id']}", "select": "*"}
        if active_only:
            params["is_active"] = "eq.true"
        return _get("searches", params)

    def get_all_searches(self) -> list[tuple[str, dict]]:
        profiles = self.get_all_linked_profiles()
        result = []
        for p in profiles:
            searches = _get(
                "searches",
                {"user_id": f"eq.{p['id']}", "is_active": "eq.true", "select": "*"},
            )
            for s in searches:
                result.append((p["telegram_chat_id"], s))
        return result

    def pause_search_for_chat(self, search_id: str, chat_id: str) -> bool:
        profile = self.get_profile_by_chat(chat_id)
        if not profile:
            return False
        rows = _patch(
            "searches",
            {"id": f"eq.{search_id}", "user_id": f"eq.{profile['id']}"},
            {"is_active": False},
        )
        return bool(rows)

    def update_search_status(self, search_id: str, match_count: int, notified: bool = False):
        now = datetime.now(timezone.utc).isoformat()
        body: dict = {"last_scanned_at": now, "last_match_count": match_count}
        if notified:
            body["last_notified_at"] = now
        _patch("searches", {"id": f"eq.{search_id}"}, body)

    def mark_notified(self, search_id: str):
        _patch(
            "searches",
            {"id": f"eq.{search_id}"},
            {"last_notified_at": datetime.now(timezone.utc).isoformat()},
        )

    # ── seen_ids + seen_prices ────────────────────────────────────────────────

    def get_seen_state(self, search_id: str) -> tuple[list[str] | None, dict]:
        """Single DB call — returns (seen_ids, seen_prices). seen_ids is None if never seeded."""
        rows = _get("searches", {"id": f"eq.{search_id}", "select": "seen_ids,seen_prices"})
        if not rows:
            return None, {}
        return rows[0].get("seen_ids"), (rows[0].get("seen_prices") or {})

    def get_seen_ids(self, search_id: str) -> list[str]:
        ids, _ = self.get_seen_state(search_id)
        return ids or []

    def get_searches_by_email(self, email: str) -> tuple[dict | None, list[dict]]:
        rows = _get("profiles", {"email": f"eq.{email}", "select": "id,email,telegram_chat_id"})
        if not rows:
            return None, []
        profile = rows[0]
        searches = _get("searches", {"user_id": f"eq.{profile['id']}", "select": "*"})
        return profile, searches

    def reset_seen_ids(self, search_id: str):
        _patch("searches", {"id": f"eq.{search_id}"}, {"seen_ids": None, "seen_prices": None})

    def mark_seen(self, search_id: str, new_ids: list[str], current: list[str] = None,
                  price_map: dict = None, current_prices: dict = None, force_write: bool = False):
        if not new_ids and not price_map and not force_write:
            return
        if current is None:
            current_ids, current_prices_fetched = self.get_seen_state(search_id)
            current = current_ids or []
            if current_prices is None:
                current_prices = current_prices_fetched
        elif current_prices is None:
            # current provided but current_prices omitted — fetch to avoid wiping seen_prices
            _, current_prices = self.get_seen_state(search_id)

        seen_set = set(current)
        merged = list(current)
        for nid in new_ids:
            if nid not in seen_set:
                merged.append(nid)
                seen_set.add(nid)
        trimmed = merged[-5000:]

        body: dict = {"seen_ids": trimmed}
        if price_map is not None:
            active = set(trimmed)
            merged_prices = {k: v for k, v in (current_prices or {}).items() if k in active}
            merged_prices.update({k: v for k, v in price_map.items() if k in active})
            body["seen_prices"] = merged_prices

        _patch("searches", {"id": f"eq.{search_id}"}, body)
        logger.debug(f"mark_seen {search_id}: {len(current)} → {len(trimmed)} ids")
